site_name: A.Cloud's Notebook
site_url: https://st-anontokyo.github.io/notebook/
nav:
  - 主页: index.md
  - 系统:
    - system/index.md
    - hpc短学期:
      - system/hpc/index.md
      - 超算概述: system/hpc/1.md
extra_css:
  - style/style.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

plugins:
  - tags

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  language: zh
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: 切换夜间模式

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-night
        name: 切换日间模式

  font:
    text: Noto Serif SC
    code: Roboto Mono

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16